<?php

declare(strict_types = 1);

namespace MemberBotBundle\Repository;

/**
 * BlockedMoneyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockedMoneyRepository extends \Doctrine\ORM\EntityRepository
{
}
