<?php

declare(strict_types = 1);

namespace MemberBotBundle\Repository;

/**
 * TransactionLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionLogRepository extends \Doctrine\ORM\EntityRepository
{
}
